### ISSUE TITLE
Reprioritization

### ISSUE THREAD

**Issue by LPardue** [kazuho/draft-kazuho-httpbis-priority#1]
Reprioritization is an important feature, the document doesn't currently mention it. Since this is a header its likely that what it represents 1) a desired initial priority from the client 2) a server override for its view of the initial priority. Once the response is in flight, the only way to do reprioritization is at the H2 or H3 framing level. 

The doc mentions the SETTINGS_HEADER_BASED_PRIORITY setting that "instructs the server that recognizes the settings parameter to use the header-based prioritization scheme instead of the frame-based prioritization scheme defined by HTTP/2". We might want a different kind of PRIORITY frame to allow reprioritzation in this scenario.

FWIW [priority hints](https://wicg.github.io/priority-hints/) (although a different proposition to this spec) API is based on element attributes and so suffers from lack of reprioritization too. Although that document uses the term, what it means to me is to override the User Agent's view of priority. One potential separate thread of work could consider a more programmatic API that allows management of priority while the response data is in flight.

**Comment by LPardue** [comment]
This also affects the priority of pushed responses, because the client has no means to send a header back

**Comment by kazuho** [comment]
I acknowledge the fact that the draft does not specify a method for a client to change the priority while the response is inflight.

If we are to allow clients reprioritize the requests, I think the answer is obvious. Define a HTTP/2 (or /3) frame that transmits the literal value of the Priority header field. That value would indicate the up-to-date priority of the request. The frame also needs to carry a boolean flag indicating whether the reprioritization request was sent before or after the client saw the response (which could include server's priority response header). Without that information, the server cannot tell if the values found in the response header should override the reprioritization instruction provided by the client.

The question is if we want to define such a frame now. My thought has been that reprioritization is not that important. I think that the only practical case that matters at the moment is for pushed responses, however my view is that servers should prioritize them (asking the browser for providing correct signal loses 1 RTT that we gain from push). The argument against such recommendation would be that people could fail to set correct precedence for push, but it is also true that browsers at the moment do not reprioritize, so meh.

Do you feel that reprioritization is a must-have? If so, I'm positive to defining the frame. If not, I think it might be better to describe the aforementioned design in the Considerations section.

WDYT?

**Comment by LPardue** [comment]
> Do you feel that reprioritization is a must-have?

Personally yes but I think this has come up in various discussion lately (although I could be mis-remembering). 

I think there are uses cases like long lived requests that can benefit, I'm not so bothered by push but it would be a shame to inadvertenly affect it.

> If so, I'm positive to defining the frame. If not, I think it might be better to describe the aforementioned design in the Considerations section.

There's a risk to getting caught up in solutionizing. So perhaps we would benefit from capturing use cases, design rationale, tradeoffs - even if very brief.

**Comment by kazuho** [comment]
> There's a risk to getting caught up in solutionizing. So perhaps we would benefit from capturing use cases, design rationale, tradeoffs - even if very brief.

Makes sense to me.

**Comment by LPardue** [comment]
While discussing extensibility on #7, we touched on the topic of reprioritzation, so reproducing some conversation from there into here before we forget.

> The Cloudflare blog [explains] a cf-priority header and a cf-priority-change header [1].
> 
> This allows something like
> 
> cf-priority = value #initial value
> cf-priority-change = 512:new value # priority value after 512 bytes of response was streamed
> 
> The advantage on using headers over frames is that the Web platform has many APIs for Headers. In contrast, HTTP/2 frames have difficulty here.

cf-priority-change header is a way to set the dynamic priority of a response apriori. In Cloudflare's use case, the header appears on responses controlled by edge-compute logic, and drives the prioritisation logic for the H2 protocol translation proxy.

Theoretically such a header could be generalised so that a client could also communicate priority changes at request initiation. However, the problem of response-in-flight prioritisation (or posteriori) reprioritization is not addressed.

[1] - https://blog.cloudflare.com/parallel-streaming-of-progressive-images/

**Comment by LPardue** [comment]
I created a Wiki page to capture some rough thoughts on how reprioritization might work:

https://github.com/kazuho/draft-kazuho-httpbis-priority/wiki/Roughing-out-reprioritization

**Comment by kazuho** [comment]
Thank you for starting the Wiki, and writing down the options. I share the view that using a frame that carries the textual representation of a Priority header field value is the way to go. The nature of the Priority header field being a comma-separated list of text means that it naturally allows vendor-specific extensions, I do not think we can define a binary encoding.

I don't have a strong opinion if the textual representation needs to support compression (e.g., HPACK).

**Comment by LPardue** [comment]
> I don't have a strong opinion if the textual representation needs to support compression (e.g., HPACK).

One line of argument, just to spur some discussion. A frame that includes **only** `Priority` header information is hard to extend. If we want to add theoretical `Priority-Enchancement` header, we need to then somehow define a new frame and link to the frame that carries `Priority` header. This has potential to add some complexity because then we might need rules for composing these frames.

One design goal might be to have atomic reprioritization commands that can be processed in a single pass. My preferred realisation is a single protocol message for that (a single frame) that can be processed in a single pass. Multiple frames make atomic commands harder because they require start/end sentinels. 

HTTP's header composition rules play nice with this design goal. Taking the above example, of `Priority` and `Priority-Enhancement` header, a frame that carries a header block can use HPACK instructions to delineate the headers in the "header list stub". I'd expect implementations to already have the machinery to support header block creation and parsing. We avoid defining bespoke rules that are harder to deploy.

An alternative is to define a more generic frame that carries a header field name and value (I actually previously considered such a frame for H2/H3 implementations that wanted to avoid compression altogther)  e.g. don't read too much into 32-length

`Header-field parameter` type:
```
+-------------------------------+-------------------------------+
|                    Header-name-len (32)                       |
+-------------------------------+-------------------------------+
|                   Header-value-len  (32)                      |
+---------------------------------------------------------------+
|                     Header-name (*) ...                       |
+---------------------------------------------------------------+
|                     Header-value (*) ...                      |
+---------------------------------------------------------------+
```

Header-based reprioritization frame contains a stream ID (target of reprioritzation) and 1 or more Header-field parameters:
```
+-------------------------------+-------------------------------+
|                          Stream ID (32)                       |
+-------------------------------+-------------------------------+
|                     Header-field parameter (*)                |
+-------------------------------+-------------------------------+
```



edit: fixed diagram

**Comment by LPardue** [comment]
In https://github.com/kazuho/draft-kazuho-httpbis-priority/pull/11#issuecomment-508079955 @kazuho presented an argument **against** using a frame that uses compression. To paraphrase:

A frame that modifies the HPACK/QPACK compression state is a semantic change. From RFC 7540, 

> Extensions that could change the semantics of existing protocol
   components MUST be negotiated before being used.

This is a drawback to one of the Priority header features - right now it can be sent optimistically with little risk of breaking the protocol in a critical way. HTTP/2 negotiation can be done via SETTINGS, which reduces the risk at the price of additional coordination (and that coordination is hard in HTTP/3 and 0-RTT).

**Comment by kazuho** [comment]
If we are to define a H2 (H3) extension that sends a "header block" mid-message, I think it should be a generic extension that uses HPACK / QPACK. We can state that the contents of the header block does not affect the HTTP message, but can be used to signal the properties of the transmission. This is somewhat analogous to the restrictions that we have for trailers.

OTOH, I am wary of using different headers (like `priority-enhancement`) that you've suggested. The primary reason is that using multiple header fields eliminates the possibility of specifying the priority value is an HTML tag (or a link header field). My preference goes to using a single header field value, so that the prioritization information (that is to be carried by the header field) can be stored in other places (e.g, within an HTML tag attribute).

**Comment by LPardue** [comment]
> OTOH, I am wary of using different headers (like priority-enhancement) that you've suggested.

I think that is a reasonable design constraint. Extensibility by "parameter only" serves the atomic processing goal I mentioned above.

> The primary reason is that using multiple header fields eliminates the possibility of specifying the priority value is an HTML tag (or a link header field). 

Is this something that is consciously in mind? Perhaps that relates to #12.

**Comment by LPardue** [comment]
We added the PRIORITY_UPDATE frame, which addresses most of the this issue and the further discussion. Any debate on the contents is not critical and not dependent on whether reprioritization is a desired feature or not. Therfore I am closing this issue as done.
