### ISSUE TITLE
Can server send PRIORITY_UPDATE?

### ISSUE THREAD

**Issue by dtikhonov** [kazuho/draft-kazuho-httpbis-priority#121]
Section 5 discusses how client can re-prioritize using the _PRIORITY_UPDATE_ frame and Section 6 discusses how the server can override priority using the `priority` header.  It seems, then, that the server cannot send the _PRIORITY_UPDATE_ frame, but it is not forbidden in the draft.

**Comment by LPardue** [comment]
Thanks for raising the issue. This is a gap in the spec and will need filling. The answer depends a little on the direction that the design takes in the WG; the salient question, I think, is: _what is the collaboration story for reprioritization?_

Once there is a answer, we can lock down some of the normative text in the TODO placeholder 

```
TODO: add more description of how to handle things like receiving PRIORITY_UPDATE on wrong stream, a PRIORITY_UPDATE with an invalid ID, etc.
```

**Comment by LPardue** [comment]
This issue is still valid but I'm migrating it to the http-extensions repo for continued discussion, https://github.com/httpwg/http-extensions/issues/1079
