### ISSUE TITLE
Server sending "SETTINGS_HEADER_BASED_PRIORITY"

### ISSUE THREAD

**Issue by rmarx** [kazuho/draft-kazuho-httpbis-priority#26]
I'm not sure on the rationale to prohibit the server from sending the "SETTINGS_HEADER_BASED_PRIORITY" parameter? 

I would agree it's not of much use to the client, but since you're targeting intermediates as well, I can assume they might want to know if they need to take server-side priorities into account or not? Might allow them to skip looking at/for those headers?

**Comment by LPardue** [comment]
I think this is a valid question. Some earlier discussion/context happened on PR https://github.com/kazuho/draft-kazuho-httpbis-priority/pull/11#issuecomment-508079955

In a nutshell, negotiation might be required depending on how the reprioritization story plays out. In the meantime, I don't think it adds much value. The client can simply send the header regardless of what servers implement or if the client actually sends the setting itself. However, if the server can send this parameter, we need to define the handling of cases when a) it's advertised and not respected b) race conditions in a protocol like H3, where priority information could arrive before settings.

**Comment by kazuho** [comment]
Closing as we no longer have this settings parameter.
