### ISSUE TITLE
Specify proper use case for background level

### ISSUE THREAD

**Issue by rmarx** [kazuho/draft-kazuho-httpbis-priority#36]
As discussed in this small thread https://github.com/kazuho/draft-kazuho-httpbis-priority/pull/34#discussion_r302464594, the background example use case of "downloading an update" doesn't really seem to fit the typical web browsing use case.

Other options: Prefetch (but that requires discussing re-prioritization), Service Worker-based updates, things like blog comments and social media plugins. 

Welcoming input from @ianswett and @pmeenan on this one as well.

**Comment by pmeenan** [comment]
Downloading an update might not but a file download should fit the bill pretty well and have similar semantics. They will be coming from web origins and sharing connections with other resources.

Updates may also end up coalesced into the same connection if a https forward proxy is configured though outside of Chrome's data reduction proxy I don't know how common they are.

Service worker background sync's if they ever see the light of day also feel like a very explicit use case for background priorities and will be normal web requests.

**Comment by rmarx** [comment]
I was thinking more about custom service-worker logic that e.g., prefetches and pre-caches resources based on a certain application-specific logic, but background sync of course is similar.

I do like the more general setup of "downloading a (large) file" as opposed to "downloading a software update". That might be the simplest change we can make to the text that is semantically correct and that is probably recognizable and logic to most readers.
