### ISSUE TITLE
Reprioritization example of the HTML file a bit unrealistic maybe

### ISSUE THREAD

**Issue by LPardue** [kazuho/draft-kazuho-httpbis-priority#53]
I feel the reprioritization example of the HTML file a bit unrealistic maybe. Are people actually prefetch-ing whole documents? I personally would change it to a prefetch-ed JavaScript request or maybe an image that was off-screen but now the user started scrolling down.  

_Originally posted by @rmarx in https://github.com/kazuho/draft-kazuho-httpbis-priority/pull/51#issuecomment-548138752_

**Comment by kazuho** [comment]
I agree that what we describe in an example should better match what the browsers actually do now or will do.

I like the idea of using an offscreen image coming into viewport (or maybe an initially hidden image that becomes visible), but I think we might prefer, for an example, using something that we all think should be initially fetched using the background level. I do not want to invoke a discussion on how a offscreen or a hidden image should be prioritized. That should be up to the browser developers.

**Comment by rmarx** [comment]
In that case, I would go with a prefetch-ed JavaScript file. This is for example commonly done for Single Page Apps that split their JavaScript based on individual "routes" in the page. They load the JS for the current route first, then start prefetching other likely routes in the background. If the user navigates early, one of those prefetches can become of highest priority.

**Comment by kazuho** [comment]
That works for me.

**Comment by rmarx** [comment]
Given this slightly out-of-hand discussion on twitter on the topic, I definitely feel we should change the example to something less contentious: https://twitter.com/programmingart/status/1189885869446049793

**Comment by junhochoi** [comment]
I think intermediate proxy can do prefetching behavior (some CDN has prefetching as a feature). In this case proxy may prefetching in low priority and switch to higher priority (if in the middle of prefetching) if client requires it with high priority.
