### ISSUE TITLE
[negotiation] Do we need an identifier for H2 prioritization scheme?

### ISSUE THREAD

**Issue by kazuho** [kazuho/draft-kazuho-httpbis-priority#67]
(We can defer this issue post IETF 106 deadline, but am raising it anyways).

#58 assigns an identifier for the H2's default prioritization scheme defined in RFC 7540 to be deprecated.

I wonder if we need it. We could simply say that for H2, the absence of SETTINGS_PRIORITIES indicates the use of the deprecated prioritization scheme.

That simplifies the design as well as better reflecting the nature of "deprecation", as it essentially forbids any new stack (that uses SETTING_PRIORITIES) from using the deprecated scheme.

**Comment by kazuho** [comment]
Relates to #65.

**Comment by kazuho** [comment]
FWIW I think I'm tempted to *not* do this after the I-D cutoff of IETF 106, as it might cause other issues.

**Comment by ianswett** [comment]
I think this was fixed in #81?

**Comment by LPardue** [comment]
I think kazuhos question was more philosophical. We do have a value (I.e. we define a codepoint) but IIUC this issue is about whether that is truly required by the design.

**Comment by LPardue** [comment]
I believe the plan to go back to simpler scheme (#100) will address this issue. There this should be resolved by the PR that resolves #100.

**Comment by LPardue** [comment]
closing this because #100 was addressed. Please reopen if you feel the need to do so.
