### ISSUE TITLE
Consider changing urgency range to 0-7

### ISSUE THREAD

**Issue by rmarx** [kazuho/draft-kazuho-httpbis-priority#78]
Current range is -1 to 6, some are in preference of 0-7 (CC @ianswett)

**Comment by kazuho** [comment]
Does the suggestion imply that 7 would have the highest precedence (i.e. prerequisite), and 6 would be the default? :)

**Comment by ianswett** [comment]
I was assuming we'd stick with SPDY style, even though it's backwards of most people's intuition, so the default would be 1?  But maybe that's a mistake.

**Comment by rmarx** [comment]
This reached consensus in Singapore: 0-7 with 0 being highest priority.
I will write up a PR for this.
