### ISSUE TITLE
GREASE priority negotiation

### ISSUE THREAD

**Issue by LPardue** [kazuho/draft-kazuho-httpbis-priority#88]
GREASE is pretty popular, if we genuinely want to define a new space for priority scheme code points we should think about protecting it. However, the 8-bit space is pretty small, which might make it unrealistic.

What do people think?

**Comment by rmarx** [comment]
I am definitely a fan of greasing! However, as you say, the space is relatively small and there is also the question if we should reserve some space for experiments (see similar recent discussion on transport parameters for QUIC) or at least how to allow experimentation, as we will probably want to do (a lot of) that in the future.

**Comment by LPardue** [comment]
Re: experimentation

I liberally borrowed the following text from H3

```
The "HTTP Prioritization Scheme" registry operates
   under either of the "IETF Review" or "IESG Approval" policies
   [RFC5226] for values between 0x00 and 0xef, with values between 0xf0
   and 0xff being reserved for Experimental Use.
```

**Comment by kazuho** [comment]
I think we have enough space for greasing.

The purpose of greasing is to let the implementors recognize that they need to handle unknown values; that means that just reserving a handful of numbers (e.g. those that can be divided by 41) is enough.

**Comment by rmarx** [comment]
> Re: experimentation
> 
> I liberally borrowed the following text from H3
> 
> ```
> The "HTTP Prioritization Scheme" registry operates
>    under either of the "IETF Review" or "IESG Approval" policies
>    [RFC5226] for values between 0x00 and 0xef, with values between 0xf0
>    and 0xff being reserved for Experimental Use.
> ```

Right, that's what I get for not reading all the latest changes, I'm sorry. Looks fine. 

> I think we have enough space for greasing.
> 
> The purpose of greasing is to let the implementors recognize that they need to handle unknown values; that means that just reserving a handful of numbers (e.g. those that can be divided by 41) is enough.

This also seems sensible.

**Comment by LPardue** [comment]
We want to go back to a boolean. You can't grease a boolean. So I'm closing this issue and I'll reopen if the thing resurfaces.
