### ISSUE TITLE
Parameter capitalization + other guidance

### ISSUE THREAD

**Issue by LPardue** [kazuho/draft-kazuho-httpbis-priority#89]
The scheme is extensible via new parameters, it seemes we might fall into all the usual traps with grammar and syntax. The First that comes to mind is capitalization. However, since we don't dedicate much text to defining urgency and progressive, I wonder if Structured Headers is carrying the burden to some extent.

**Comment by kazuho** [comment]
Agreed. We only need to define the case sensitivity of the parameter names.

And I'd assume that they are to be specified case-insensitive.

**Comment by LPardue** [comment]
Agreed. Are SH dictionary item names normally case-sensitive?

**Comment by kazuho** [comment]
Reading https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#rfc.section.3.2, I think SH leaves that up to us.

I also realize that we also need to talk about what to do when facing a name used more than once. Maybe use the last one?

**Comment by LPardue** [comment]
From SH I think it is clear it must be lower case

```
sh-dictionary  = dict-member *( OWS "," OWS dict-member )
dict-member    = member-name "=" member-value
member-name    = key
member-value   = sh-item / inner-list
```

```
key           = lcalpha *( lcalpha / DIGIT / "_" / "-" / "*" )
lcalpha       = %x61-7A ; a-z
```

**Comment by LPardue** [comment]
Regrading dplicates that seems totally disallowed

```
Let dictionary be an empty, ordered map.
While input_string is not empty:

    Let this_key be the result of running Parsing a Key (Section 4.2.3.3) with input_string.
    If dictionary already contains the name this_key, there is a duplicate; fail parsing.
```

**Comment by kazuho** [comment]
Thank you for checking! Of course you are correct for the two.

**Comment by LPardue** [comment]
Closing because no problem. Will open separate issue if there is a specific guidance point I can think of that is not covered.
