### ISSUE TITLE
Shorten header field names

### ISSUE THREAD

**Issue by rmarx** [kazuho/draft-kazuho-httpbis-priority#96]
Discussed in Singapore: mainly to reduce overhead on H1, we would want to shorten the field names (e.g., urgency becomes u, progressive becomes p). 

Concrete example was   3;p   to indicate  urgency level 3, progressive=?1 (I assume leaving out the p means progressive=?0)

I don't know enough about structured headers to make these changes myself though.

**Comment by rmarx** [comment]
Maybe this is a good opportunity to rename progressive to incremental as well, as per #35

**Comment by LPardue** [comment]
Since I wasn't at the face-to-face, this sounds like it has overlap with #90. I'd like to resolve my understanding of the linkage between these two issues, so perhaps need to wait for the PR that addresses this one.

**Comment by rmarx** [comment]
Wasn't extensive discussion on #90 in Singapore, but talked with @kazuho about this, and he said he felt #90 should be out-of-scope for now can be punted till later. I tend to agree with that.

**Comment by ianswett** [comment]
Agreed, I think #90 is a more complex use case than we've had time to seriously consider.

**Comment by rmarx** [comment]
Current text says 

> Values of these parameters MUST always be present.

This should also be changed then (e.g., leaving out progressive leads to default value). Apparently, this is also not enforced in all the examples in the current text.

**Comment by rmarx** [comment]
After some discussion with @kazuho  and @LPardue, it seems structured header dictionaries need the values present for each parameter, so it would look like this (i = incremental)

> priority: u=0, i=?0

If that's correct, I can take this one up as well.

**Comment by ianswett** [comment]
I think that's the most obvious change, so I'd suggest proceeding with that.
