### ISSUE TITLE
Talk about caching issues stemming from HEADERS-based approach

### ISSUE THREAD

**Issue by rmarx** [kazuho/draft-kazuho-httpbis-priority#97]
Discussed in Singapore. Caching-issues related to header-based approach are difficult, but part of "normal HTTP". 

We should provide guidance though and list the foreseen gotcha's to prevent people from making obvious mistakes.

I don't have enough experience to know what those gotcha's actually are, but e.g., stripping header when storing in cache, interaction with Vary, etc. are things I've heard multiple times. cc @ianswett

**Comment by LPardue** [comment]
Who does have the expertise to get this guidance correct-as-possible for the next cut of the draft?

**Comment by rmarx** [comment]
I would say we include @ianswett's initial comments now. Roy also had some points and I think @kazuho also had some insights. It doesn't have to be perfect for now, Mark literally said he'd be fine with a "(this list is incomplete and requires more in-depth discussion)" in the draft that goes to the call for adoption.

**Comment by ianswett** [comment]
I don't think I'm the best person, but I can take a stab at it.

At lunch, use of the "vary" and "no-cache" were mentioned as items to mention explicitly.
 vary: https://tools.ietf.org/html/rfc7231#section-7.1.4
 no-cache: https://tools.ietf.org/html/rfc7234#section-5.2.2.2

**Comment by c-taylor** [comment]
Suggested text:

Origin priority headers sent with the response will be cached according to standard HTTP caching behaviour and re-used for subsequent requests. Origins that require priority NOT to be cached should exclude the header from the response or use standard HTTP Cache-Control methods to exclude or vary on the header.

**Comment by kazuho** [comment]
I think the text by @c-taylor covers the aspects we need to cover.
